// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHZAldkI0qRM90m6DC1zF65m756S1vdcU',
    appId: '1:881287164458:web:091c385cf07c800c084953',
    messagingSenderId: '881287164458',
    projectId: 'automarket619',
    authDomain: 'automarket619.firebaseapp.com',
    storageBucket: 'automarket619.firebasestorage.app',
    measurementId: 'G-K44SZZLJB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5NSiY76Nt_L-40SpGyUIy9cLc89eiIuo',
    appId: '1:881287164458:android:ed064864795bba61084953',
    messagingSenderId: '881287164458',
    projectId: 'automarket619',
    storageBucket: 'automarket619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KOwH1Lfhu-F1CH5YG28omR4oltKeJwo',
    appId: '1:881287164458:ios:e4b4dcd2ef63f30c084953',
    messagingSenderId: '881287164458',
    projectId: 'automarket619',
    storageBucket: 'automarket619.firebasestorage.app',
    iosBundleId: 'com.example.automarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1KOwH1Lfhu-F1CH5YG28omR4oltKeJwo',
    appId: '1:881287164458:ios:e4b4dcd2ef63f30c084953',
    messagingSenderId: '881287164458',
    projectId: 'automarket619',
    storageBucket: 'automarket619.firebasestorage.app',
    iosBundleId: 'com.example.automarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHZAldkI0qRM90m6DC1zF65m756S1vdcU',
    appId: '1:881287164458:web:f394a5a04adc2d82084953',
    messagingSenderId: '881287164458',
    projectId: 'automarket619',
    authDomain: 'automarket619.firebaseapp.com',
    storageBucket: 'automarket619.firebasestorage.app',
    measurementId: 'G-34KRVKGBZ9',
  );
}
